package(default_visibility = ["//visibility:public"])

cc_test(name = "module_dispatcher_test",
        srcs = ["module_dispatcher_test.cc"],
        deps = [
            "//cc:module_dispatcher",
            "@google_googletest//:gtest",
            "@google_googletest//:gtest_main",
        ])
